branch-defaults:
  default:
    environment: node-express-env
    group_suffix: null
  master:
    environment: lil-shipbuilders-env
global:
  application_name: node-express
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
